# -*- coding: utf-8 -*-
"""PROJETO 02(MUITO IMPORTANTE) BANCO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I1f9CtRvPXdKzUhfgharKbggbp8Y4vNw
"""

lista_contas = []


#SIMULADOR DE UM FLUXO BANCÁRIO
print('>>>>> Bem-vindo ao Banco do Genzo <<<<<')

programa_on = True
#------------------MENU
while programa_on == True:
  print("\n[[[[[[ MENU ]]]]]]")
  print("--------------\n>>> 0 - Sair <<<")
  print("--------------\n>>> 1 - Criar Conta <<<\n--------------")
  print(">>> 2 - Deletar uma Conta <<<\n--------------")
  print(">>> 3 - Listar Contas <<<\n-------------")
  print(">>> 4 - Adicionar Saldo <<<\n-------------")
  print(">>> 5 - Remover Saldo <<<\n-------------")
  print(">>> 6 - Transferência <<<\n-------------")
  print(">>> 7 - Consultar Saldo de uma Conta <<<\n---------------")
  programa_operacao = input('>>>>> \nPor favor digite a ação desejada:\n>>>> ')

#------------------ENCERRAR OPERAÇÃO
  if programa_operacao == '0':
    print("\nEncerrando Operação...")
    programa_on = False

#------------------CRIAR CONTA
  elif programa_operacao == '1':
    verificador_conta = False
    dados_nova_conta = {}
    dados_nova_conta['numero_conta'] = input('\nNos informe o número da sua nova conta:\n>>>> ')

    for consulta_conta in lista_contas:
      if consulta_conta['numero_conta'] == dados_nova_conta['numero_conta']:
        verificador_conta = True


    if verificador_conta == True:
      print('-----------------------\nVocê colocou um número de conta que ja existe!\n---------------------------')

    else:
      dados_nova_conta['saldo_conta'] = float(input('\nPor favor insira o seu saldo:\n>>>> '))
      lista_contas.append(dados_nova_conta)
      print('\nOperação efetuada com sucesso')

#---------------------REMOVER CONTA
  elif programa_operacao == '2':
    verificador_delete = False
    dados_para_deletar = {}
    dados_para_deletar['numero_conta'] = input('\nNos informe o número da sua conta para deletarmos\n----> ')

    for consulta_conta in lista_contas:
      if consulta_conta['numero_conta'] == dados_para_deletar['numero_conta']:
        verificador_delete = True
        break

    if verificador_delete == True:
      print('\nOtímo sua conta foi encontrada, nos informe agora o saldo que possui na sua conta, para devolvermos')
      dados_para_deletar['saldo_conta'] = float(input('-----> '))
      lista_contas.remove(dados_para_deletar)
      print('\nSeus dados foram deletados com sucesso')
    else:
      if verificador_delete == False:
        print('\nDados não encontrados, tente de novo.')


#-----------------------LISTAR CONTAS

  elif programa_operacao == '3':
    if len(lista_contas) == 0:
      print('\nNão há nenhuma conta cadastrada no momento!')
    else:
      if len(lista_contas) > 0:
        for listar_contas in lista_contas:                   #AQUI NO SALDO USAREI UMA FUNÇÃO PRA FORMATAR A QUANTIDADE DE CASAS APÓS A VIRGULA. #:.2f
          print("Conta: ", listar_contas['numero_conta'], 'Saldo: ', listar_contas["saldo_conta"], 'R$')

#-----------------------ADICIONAR SALDO

  elif programa_operacao == '4':
    print("\nOlá, antes de continuarmos por favor insira o número da sua conta no campo abaixo:")
    conta_para_add_saldo = {}
    conta_para_add_saldo = input('----> ')
    for verificador_conta_saldo in lista_contas:
      if verificador_conta_saldo['numero_conta'] == conta_para_add_saldo:
        print("Conta encontrada com sucesso.")
        print("\nÓtimo, Quanto você deseja adicionar a sua conta?")
        saldo_add = float(input('----> '))
        if saldo_add <= 0:
          print('--------------\nTente novamente.\n--------------')

        else:
          if saldo_add > 0:
           verificador_conta_saldo['saldo_conta'] += saldo_add
           print("\nSeu dinheiro foi adicionado!")
        break
    else:
      if verificador_conta_saldo['numero_conta'] != conta_para_add_saldo:
        print("--------------\nSeus dados estão errados\n---------------")

#----------------------------------REMOVER SALDO

  elif programa_operacao == '5':
    print("\nÓtimo, antes de continuar, por favor digite o número da sua conta abaixo")
    remover_saldo = {}
    remover_saldo['numero_conta'] = input('-----> ')
    for remover_saldo_conta in lista_contas:
      if remover_saldo['numero_conta'] == remover_saldo_conta['numero_conta']:
        print("Ótimo sua conta foi encontrada")
        print('\nPor favor, digite o saldo a ser retirado da sua conta.')
        saldo_removido = float(input('------> '))
        if saldo_removido > 0 and saldo_removido <= remover_saldo_conta['saldo_conta']:
          remover_saldo_conta['saldo_conta'] -= saldo_removido
        else:
          if saldo_removido <= 0 or saldo_removido > remover_saldo_conta['saldo_conta']:
            print('Operação Inválida.')
      else:
        if remover_saldo['numero_conta'] != remover_saldo_conta['numero_conta']:
          print('Sua conta nao foi encontrada, tente novamente.')


#---------------------------------TRANSFERIR SALDO
  elif programa_operacao == '6':
    print('\nPor favor insira a número da sua conta para continuarmos.')
    conta_partida = {}
    conta_partida['numero_conta'] = input('-----> ')
    verificador = 0
    for conta_em_consulta in lista_contas:
      if conta_em_consulta['numero_conta'] == conta_partida['numero_conta']:
        verificador = 1
        #ACHOU A PRIMEIRA
        print('\nÓtimo achamos sua conta, qual a conta em que você depositará um valor?')
        conta_destino = {}
        conta_destino['numero_conta'] = input('-----> ')
        if conta_destino['numero_conta'] != conta_partida['numero_conta']:
          for conta_em_consulta_2 in lista_contas:
             if conta_destino['numero_conta'] == conta_em_consulta_2['numero_conta']:
                verificador = 2
              #ACHOU AS DUAS
                print('\nAchamos a conta no qual você irá depositar o saldo. \nQuanto você quer Trasferir?')
                valor_transferido = float(input('------> '))
                if valor_transferido > 0 and valor_transferido <= conta_em_consulta['saldo_conta']:
                  conta_em_consulta['saldo_conta'] -= valor_transferido
                  conta_em_consulta_2['saldo_conta'] += valor_transferido
                  verificador = 3

                else:
                  if valor_transferido <= 0:
                    print("OPERAÇÃO INVÁLIDA")

             else:
              if conta_destino['numero_conta'] != conta_em_consulta_2['numero_conta']:
                 print()
        else:
          if conta_destino['numero_conta'] == conta_partida['numero_conta']:
            print()

      else:
        if conta_em_consulta['numero_conta'] != conta_partida['numero_conta']:
           print()

    if verificador == 0:
      print('NAO FOI POSSIVEL ACHAR SUA CONTA')

    elif verificador == 1:
        print('CONTA DE DESTINO NÃO ENCONTRADA')

    elif verificador == 2:
      print('AS DUAS CONTAS FORAM VÁLIDADAS, PORÉM O SALDO É INVÁLIDO')

    elif verificador == 4:
      print('OPERAÇÃO EFETUADA')

    else:
      if verificador == 3:
        print('OPERACAO EFETUADA')

#---------------------------------------------CONSULTAR SALDO DE UMA CONTA

  else:
    if programa_operacao == '7':
      print('\nPor favor digite o número da conta na qual deseja acessar o saldo')
      conta_verificacao = {}
      conta_verificacao['numero_conta'] = input('-----> ')
      indice = 0
      for verificacao_existe in lista_contas:
        if conta_verificacao['numero_conta'] == verificacao_existe['numero_conta']:
          print('--------------------------\nSeu saldo é de R$: ',verificacao_existe['saldo_conta'])
          break
        else:
          if conta_verificacao['numero_conta'] != verificacao_existe['numero_conta']:
           fodase = None

